### ISSUE TITLE
t42 failed

### ISSUE THREAD

**Issue by loo66** [petelomax/Phix#4]
Hi,

t42 failed on Ubuntu 20.04, 64 Bit with Phix 0.8.3 - see below.

Greetings
Otto

```
Testing[42]: /home/thales/phix/test/t42cback.exw
-77
-77
hello pete
1
1
hello pete
hello pete
{{0}}
hello pete
{{2}}
3
3
hello pete
{{2}}
3
3
handler: 1 2 3 4
handler: #00000001 2 3 4
10
10
handler: 1 2 3 4
handler: #00000001 2 3 4
10
10
-1
  the result of 7 * 8.50 is: 4.85876e-309
```

**Comment by petelomax** [comment]
Thanks, that is in fact a silly hand-crafted test based on **_my_** misunderstanding of the lnx 64-bit calling convention, which was recently fixed. The test itself, lines 381..440 aka "Example #3" .. "14/08/2010 thanks to Les Bothwell" in test/t42cback.exw has simply been commented out here, a couple of days ago (since **_me_** attempting to "fix" it would probably still somehow be wrong).
