### ISSUE TITLE
64 bit crash on Ubuntu with uninitialized vars

### ISSUE THREAD

**Issue by loo66** [petelomax/Phix#7]
Hi again,

seems there are still several 64/32 issues. On Win32 the "variable not assigned" message comes nicely for the return statement,  on Ubuntu64 we get a segmentation fault ...

Cheers
Otto 

> function p1()
>   atom a, b
> 
>   a = 1
>   if false then
>     b = 2
>   end if  
>   
>   return {a,b}
> end function
> 
> ?p1()

**Comment by petelomax** [comment]
Thanks, I've just pushed a fixed pDiagN.e to the repository (nb only tested on win64, and probably best to only copy the one file).
[Getting all should be fine, but I've just done a major restructure for eval() so yet again there's a potential time bomb for someone to get half-and-half, and/or end up with something from some unknown midpoint that I can't properly support.]

Update: I now see that I had a go at fixing that 5 years ago but failed, probably just because I forgot to peek 7 bytes on 64bit.

Sorry for the inconvenience, but from my perspective you're doing excellent work, keep it up!
